services:
    db:
        image: postgres:18
        container_name: db-lett-faktura
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: lett_faktura
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U postgres -d lett_faktura -h localhost -p 5432",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
        networks:
            - lett_faktura_network

    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: server-lett-faktura
        environment:
            NODE_ENV: development
            PORT: 3000
            DATABASE_URL: postgresql://postgres:123456@db:5432/lett_faktura
            JWT_ACCESS_SECRET: dfkgkkjgbkdjfbvkebliuilwwiiilzp
            JWT_REFRESH_SECRET: lzvpoiaheuirabvkadbjhbbvhjvzdkhwe
            SALT_ROUNDS: 12
        ports:
            - 3000:3000
        depends_on:
            db:
                condition: service_healthy
        networks:
            - lett_faktura_network
        command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run start"

networks:
    lett_faktura_network:
        driver: bridge

volumes:
    postgres_data:
        driver: local
